language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env:
            - SYMFONY_VERSION='3.4.*'
        - php: 7.1
          env:
            - COMPOSER_FLAGS=--prefer-lowest

before_install:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
    - sh -c 'echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer config "platform.ext-mongo" "1.6.16" && composer update $COMPOSER_FLAGS --prefer-dist

script: if [[ "$TRAVIS_PHP_VERSION" == "7.1" && -z "$SYMFONY_VERSION" && -z "$COMPOSER_FLAGS" ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
